version: '3'
services:
  opencv-cpu:
    network_mode: host
    image: openhps/opencv-nodejs:ubuntu20.04-node20-opencv4.8.1-contrib
    container_name: 'opencv-cpu'
    volumes: 
    - ./:/opt/app
    - node_modules:/opt/app/node_modules/
  opencv-cuda:
    network_mode: host
    image: openhps/opencv-nodejs:ubuntu20.04-node20-opencv4.8.1-contrib-cuda
    container_name: 'opencv-cuda'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes: 
    - ./:/opt/app
    - node_modules:/opt/app/node_modules/
  opencvjs-build:
    image: emscripten/emsdk:2.0.10
volumes:
  node_modules: