name: Docker

on:
  workflow_dispatch:

jobs:
  docker:
    name: Build docker container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-version:
          - 18.04
        node-version:
          - 14
        opencv-version:
          - 3.4.15
          - 4.5.5
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
            OPENCV_VERSION=${{ matrix.opencv-version }}
            NODE_VERSION=${{ matrix.node-version }}
          context: "./docker"
          file: "./docker/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/opencv-nodejs:ubuntu${{ matrix.ubuntu-version }}-node${{ matrix.node-version }}-opencv${{ matrix.opencv-version }}