name: OpenCV.js

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OpenCV.js
    runs-on: ubuntu-latest
    strategy:
        matrix:
            opencv-version:
                - 4.6.0
                - 4.8.1
            opencv-contrib:
                - true
                - false
    container:
      image: emscripten/emsdk:2.0.10
    steps:
        - uses: actions/checkout@v3
        - name: Get number of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores
        - name: Getting OpenCV
          run:
            set -x && \
            wget -O opencv_${{ matrix.opencv-version }}.zip https://github.com/opencv/opencv/archive/${{ matrix.opencv-version }}.zip && \
            unzip -q opencv_${{ matrix.opencv-version }}.zip && \
            rm -rf opencv_${{ matrix.opencv-version }}.zip && \
            if [ -n "${{ matrix.opencv-contrib }}" ]; then \
                wget -O opencv_contrib_${{ matrix.opencv-version }}.zip https://github.com/opencv/opencv_contrib/archive/${{ matrix.opencv-version }}.zip; \
                unzip -q opencv_contrib_${{ matrix.opencv-version }}.zip; \
                rm -rf opencv_contrib_${{ matrix.opencv-version }}.zip; \
            fi